# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkra1nToolchain < Formula
    desc "checkra1n build toolchain"
    homepage "https://github.com/checkra1n/toolchain"
    depends_on :macos

    # TODO: Temporary hack to allow adding this tap while these formulae are incomplete
    url "file:///dev/null"
    sha256 "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    version "0.0.0"
    
end