# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkra1nToolchain < Formula
    desc "checkra1n build toolchain"
    homepage "https://github.com/checkra1n/toolchain"
    depends_on :macos

    
end