# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LdidSbinger < Formula
    desc "ldid with sbingner's extensions"
    homepage "https://github.com/sbingner/ldid"
    version "2.1.4"
    depends_on :macos

    
end