# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LdidSbingner < Formula
    desc "ldid with sbingner's extensions"
    homepage "https://github.com/sbingner/ldid"
    version "2.1.4"
    depends_on :macos

    # TODO: Temporary hack to allow adding this tap while these formulae are incomplete
    url "file:///dev/null"
    sha256 "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    
end