# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scgen < Formula
  desc "Docker Secure Computing Profile Generator"
  homepage "https://github.com/blacktop/seccomp-gen"
  version "1.1.5"

  on_macos do
    url "https://github.com/blacktop/seccomp-gen/releases/download/v1.1.5/scgen_1.1.5_macOS_universal.tar.gz"
    sha256 "c7b4dcf3279e4ce9b89c125cfd86d21bacdc92e5c6518d80e0f16f676894091a"

    def install
      bin.install "scgen"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blacktop/seccomp-gen/releases/download/v1.1.5/scgen_1.1.5_linux_arm64.tar.gz"
      sha256 "d5910fffeb006438b5e91d3b320f0113337aa232fa9da8016a284c156d0e24a6"

      def install
        bin.install "scgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/blacktop/seccomp-gen/releases/download/v1.1.5/scgen_1.1.5_linux_x86_64.tar.gz"
      sha256 "853dc658089f473477b56feaf70395900419f391af126621add53924a0a98fa8"

      def install
        bin.install "scgen"
      end
    end
  end

  test do
    system "#{bin}/scgen --version"
  end
end
