# This file was generated by GoReleaser. DO NOT EDIT.
class WaitForEs < Formula
  desc "Wait until Elasticsearch become available"
  homepage "https://github.com/blacktop/wait-for-es"
  url "https://github.com/blacktop/wait-for-es/releases/download/v0.1.3/wait-for-es_0.1.3_MacOS_64-bit.tar.gz"
  version "0.1.3"
  sha256 "e091a2bfb06ae59a44c88aeeedf34c756e3984d50496a545ff46ccad4216e7f7"

  def install
    bin.install "wait-for-es"
  end

  test do
    system "#{bin}/wait-for-es --version"
  end
end
